Biblioteca/Biblioteca.Frontend/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Biblioteca.Frontend.Models;
using Biblioteca.Frontend.Services;
using System.Text;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authorization;

namespace Biblioteca.Frontend.Controllers
{
    [Authorize]
    public class LibrosController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IServicioLista _servicioLista;

        public LibrosController(IHttpClientFactory httpClientFactory, IServicioLista servicioLista)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:7055/");
            _servicioLista = servicioLista;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _servicioLista.GetUsuarioByEmail(User.Identity!.Name!);
            var apiService = new ServicioToken();
            var token = await apiService.Autenticar(user);
            // Realiza la solicitud HTTP al endpoint protegido
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await _httpClient.GetAsync("/api/Libros");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var libros = JsonConvert.DeserializeObject<IEnumerable<Libro>>(content);
                return View("Index", libros);
            }

            return View(new List<Libro>());
        }

        public async Task<IActionResult> Create()
        {
            Libro libro = new()
            {
                Categorias = await _servicioLista.GetListaCategorias(),
                Estado = "Disponible"
            };
            return View(libro);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Libro libro)
        {
            //libro.Estado = "Disponible";
            var respuesta = await _httpClient.GetAsync("/api/Libros");
            var contenido = await respuesta.Content.ReadAsStringAsync();
            var libros = JsonConvert.DeserializeObject<IEnumerable<Libro>>(contenido);
            var lastCodigo = libros.OrderByDescending(x => x.Id).Select(c => c.Codigo).FirstOrDefault();
            int lastNumber = 0;
            if (!string.IsNullOrEmpty(lastCodigo) && lastCodigo.Length > 2)
            {
                int.TryParse(lastCodigo.Substring(2), out lastNumber);
            }
            libro.Codigo = $"CL{(lastNumber + 1).ToString("D5")}";

            var json = JsonConvert.SerializeObject(libro);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("/api/Libros/", content);
            if (response.IsSuccessStatusCode)
            {
                TempData["AlertMessage"] = "Libro creado exitosamente!!!";
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Error al crear el libro.");
            }
            libro.Categorias = await _servicioLista.GetListaCategorias();
            return View(libro);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Libros/{id}");
            if (!response.IsSuccessStatusCode)
            {
                TempData["ErrorMessage"] = "Error al obtener el libro.";
                return RedirectToAction("Index");
            }

            var jsonString = await response.Content.ReadAsStringAsync();
            var libro = JsonConvert.DeserializeObject<Libro>(jsonString);
            libro.Categorias = await _servicioLista.GetListaCategorias();

            return View(libro);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Libro libro)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(libro);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync($"/api/Libros/{id}", content);
                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Libro actualizado exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Error al actualizar el cliente.";
                    return RedirectToAction("Index");
                }
            }
            libro.Categorias = await _servicioLista.GetListaCategorias();
            return View(libro);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Libros/{id}");

            if (response.IsSuccessStatusCode)
            {
                TempData["AlertMessage"] = "Libro actualizado exitosamente!!!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Error al eliminar el libro.";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Solicitud(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Libros/{id}");
            if (!response.IsSuccessStatusCode)
            {
                TempData["ErrorMessage"] = "Error al obtener el libro.";
                return RedirectToAction("Index");
            }

            var jsonString = await response.Content.ReadAsStringAsync();
            var libro = JsonConvert.DeserializeObject<Libro>(jsonString);

            var email = Uri.EscapeDataString(User.Identity.Name);
            var userResponse = await _httpClient.GetAsync($"/api/Usuarios/email/{email}");
            var usuarioJson = await userResponse.Content.ReadAsStringAsync();
            var usuario = JsonConvert.DeserializeObject<Usuario>(usuarioJson);

            Prestamo prestamo = new()
            {
                UsuarioId = usuario.Id,
                Usuario = usuario,
                Libro = libro,
                LibroId = libro.Id,
                EstadoPrestamo = "Reservado",
                FechaPrestamo = DateTime.Now
            };
            return View(prestamo);
        }

        [HttpPost]
        public async Task<IActionResult> Solicitud(Prestamo prestamo)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(prestamo);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Prestamos/", content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Prestamo creado exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    var errorMessage = await response.Content.ReadAsStringAsync();
                    TempData["ErrorMessage"] = $"Error al crear el prestamo: {errorMessage}";
                    return RedirectToAction("Index");
                }
            }

            return View(prestamo);
        }
    }
}

Biblioteca/Biblioteca.Frontend/Controllers/PrestamosController.cs
using Biblioteca.Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Biblioteca.Frontend.Models;
using System.Text;
using System.Reflection;

namespace Biblioteca.Frontend.Controllers
{
    public class PrestamosController : Controller
    {

        private readonly HttpClient _httpClient;
        private readonly IServicioLista _servicioLista;

        public PrestamosController(IHttpClientFactory httpClientFactory, IServicioLista servicioLista)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:7055/");
            _servicioLista = servicioLista;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _httpClient.GetAsync("/api/Prestamos");

            if (response.IsSuccessStatusCode)
            {
                var email = Uri.EscapeDataString(User.Identity.Name);
                var userResponse = await _httpClient.GetAsync($"/api/Usuarios/email/{email}");
                var usuarioJson = await userResponse.Content.ReadAsStringAsync();
                var usuario = JsonConvert.DeserializeObject<Usuario>(usuarioJson);

                var content = await response.Content.ReadAsStringAsync();
                var prestamos = JsonConvert.DeserializeObject<IEnumerable<Prestamo>>(content);

                if (usuario.RolUsuario == Roles.Lector)
                {
                    var misPrestamos = prestamos.Where(p => p.Usuario.Correo == usuario.Correo);
                    return View("Index", misPrestamos);
                }
                                
                return View("Index", prestamos);
            }

            return View(new List<Prestamo>());
        }

        public async Task<IActionResult> Create()
        {
            Prestamo prestamo = new()
            {
                //Clientes = await _servicioLista.GetListaClientes(),
                Libros = await _servicioLista.GetListaLibros(),
                EstadoPrestamo = "Pendiente"
            };
            return View(prestamo);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Prestamo prestamo)
        {
            if (ModelState.IsValid)
            {
                var email = Uri.EscapeDataString(User.Identity.Name);
                var userResponse = await _httpClient.GetAsync($"/api/Usuarios/email/{email}");
                var usuarioJson = await userResponse.Content.ReadAsStringAsync();
                var usuario = JsonConvert.DeserializeObject<Usuario>(usuarioJson);
                prestamo.Usuario = usuario;
                prestamo.UsuarioId = usuario.Id;
                prestamo.EstadoPrestamo = "Pendiente";
                prestamo.FechaPrestamo = DateTime.Now;                                
                var json = JsonConvert.SerializeObject(prestamo);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Prestamos/", content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Prestamo creado exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al crear el prestamo.");
                }
            }
            prestamo.Libros = await _servicioLista.GetListaLibros();
            //prestamo.Clientes = await _servicioLista.GetListaClientes();
            return View(prestamo);
        }

        public async Task<IActionResult> Devolucion(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Prestamos/{id}");
            if (!response.IsSuccessStatusCode)
            {
                TempData["ErrorMessage"] = "Error al obtener el prestamo";
                return RedirectToAction("Index");
            }

            var jsonString = await response.Content.ReadAsStringAsync();
            var prestamo = JsonConvert.DeserializeObject<Prestamo>(jsonString);

            return View(prestamo);
        }

        [HttpPost]
        public async Task<IActionResult> Devolucion(int id, Prestamo prestamo)
        {
            if (ModelState.IsValid)
            {
                prestamo.FechaDevolucion = DateTime.Now;
                prestamo.EstadoPrestamo = "Disponible";
                var json = JsonConvert.SerializeObject(prestamo);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync($"/api/Prestamos/{id}", content);
                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Libro devuelto exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Error al intentar realizar la devolucion.";
                    return RedirectToAction("Index");
                }
            }

            return View(prestamo);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Prestamos/{id}");

            if (response.IsSuccessStatusCode)
            {
                TempData["AlertMessage"] = "Prestamo eliminado exitosamente!!!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Error al eliminar el prestamo.";
                return RedirectToAction("Index");
            }
        }
    }
}

Biblioteca/Biblioteca.Frontend/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using Biblioteca.Frontend.Models;
using Biblioteca.Frontend.Services;

namespace Biblioteca.Frontend.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IServicioLista _servicioLista;

        public UsuariosController(IHttpClientFactory httpClientFactory, IServicioLista servicioLista)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:7055/");
            _servicioLista = servicioLista;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _httpClient.GetAsync("/api/Usuarios");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var usuarios = JsonConvert.DeserializeObject<IEnumerable<Usuario>>(content);
                return View("Index", usuarios);
            }

            return View(new List<Usuario>());
        }

        public IActionResult Create()
        {
            Usuario usuario = new()
            {
                Estado = "Activo"
            };
            return View(usuario);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Usuario usuario)
        {
            if (ModelState.IsValid)
            {               
                usuario.RolUsuario = Roles.Bibliotecario;
                usuario.Estado = "Activo";
                var json = JsonConvert.SerializeObject(usuario);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Login/Registro", content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("IniciarSesion", "Login");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error, no se pudo crear el usuario");
                }
            }
            return View(usuario);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Usuarios/{id}");
            if (!response.IsSuccessStatusCode)
            {
                TempData["ErrorMessage"] = "Error al obtener el usuario";
                return RedirectToAction("Index");
            }

            var jsonString = await response.Content.ReadAsStringAsync();
            var usuario = JsonConvert.DeserializeObject<Usuario>(jsonString);

            return View(usuario);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(usuario);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync($"/api/Usuarios/{id}", content);
                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Usuario actualizado exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Error al actualizar el usuario.";
                    return RedirectToAction("Index");
                }
            }
            return View(usuario);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Usuarios/{id}");

            if (response.IsSuccessStatusCode)
            {
                TempData["AlertMessage"] = "Usuario eliminado exitosamente!!!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Error al eliminar el usuario";
                return RedirectToAction("Index");
            }
        }
    }
}

Biblioteca/Biblioteca.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca.Frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Biblioteca.Frontend.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-info">
            <div class="container-fluid">
                <a class="navbar-brand text-light" href="#">Biblioteca Pro</a>
                <button class="navbar-toggler text-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Biblioteca Pro</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"></a>
                            </li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Administrador"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Menu
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                                        <li><a class="dropdown-item" asp-controller="Libros" asp-action="Index">Libros</a></li>
                                        <li><a class="dropdown-item" asp-controller="Clientes" asp-action="Index">Clientes</a></li>
                                        <li><a class="dropdown-item" asp-controller="Categorias" asp-action="Index">Categorias</a></li>                                        
                                        <li><a class="dropdown-item" asp-controller="Usuarios" asp-action="Index">Usuarios</a></li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li><a class="dropdown-item" asp-controller="Prestamos" asp-action="Index">Prestamos</a></li>
                                        
                                    </ul>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Lector"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Bibliotecario"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Prestamos" asp-action="Index">Prestamos</a>
                                </li>
                            }
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios"
                                       asp-action="Edit"><strong>Hola! @User.Identity.Name</strong></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="CerrarSesion">Cerrar Sesión</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="IniciarSesion">Iniciar Sesión</a>
                                </li>
                            }

                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BibliotecaPro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Biblioteca/Biblioteca.Frontend/Views/Shared/_ModalEliminar.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"> </i> No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete"><i class="fa fa-check-circle"> </i> Sí</button>
            </div>
        </div>
    </div>
</div>

Biblioteca/Biblioteca.Frontend/Views/Shared/_MostrarModal.cshtml
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss=" modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}