Biblioteca/Biblioteca.Frontend/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;

namespace Biblioteca.Frontend.Models
{
    public class Categoria
    {
        public int Id { get; set; }

        [MaxLength(100, ErrorMessage = "El campo {0} debe tener máximo {1} caractéres.")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [Display(Name = "Categoria")]
        public string Nombre { get; set; }

        [Display(Name = "Fecha de Creación")]
        public DateTime FechaCreacion { get; set; } = DateTime.Now;
    }
}

Biblioteca/Biblioteca.Frontend/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Biblioteca.Frontend.Models;
using System.Text;

namespace Biblioteca.Frontend.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly HttpClient _httpClient;

        public CategoriasController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:7055/");
        }
        public async Task<IActionResult> Index()
        {
            var response = await _httpClient.GetAsync("/api/Categorias");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var categorias = JsonConvert.DeserializeObject<IEnumerable<Categoria>>(content);
                return View("Index", categorias);
            }

            return View(new List<Categoria>());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(categoria);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Categorias/", content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Categoria creada exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al crear el categoria.");
                    TempData["ErrorMessage"] = "Ocurrió un error al intentar crear la categoria!!!";
                }
            }
            else
            {               
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                TempData["ModelErrors"] = string.Join("\n", errors);
            }
            return View(categoria);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Categorias/{id}");
            if (!response.IsSuccessStatusCode)
            {
                TempData["ErrorMessage"] = "Error al obtener la categoria.";
                return RedirectToAction("Index");
            }

            var jsonString = await response.Content.ReadAsStringAsync();
            var categoria = JsonConvert.DeserializeObject<Categoria>(jsonString);

            return View(categoria);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(categoria);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync($"/api/Categorias/{id}", content);
                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Categoria actualizada exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Error al actualizar la categoria.";
                    return RedirectToAction("Index");
                }
            }
            return View(categoria);
        }


        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Categorias/{id}");

            if (response.IsSuccessStatusCode)
            {
                TempData["AlertMessage"] = "Categoria eliminada exitosamente!!!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Error al eliminar la categoria.";
                return RedirectToAction("Index");
            }
        }
    }
}

Biblioteca/Biblioteca.Frontend/Views/Categorias/Create.cshtml
@model Biblioteca.Frontend.Models.Categoria
@{
    ViewData["Title"] = "Create";
    Layout = null;
}



<div class=" col-md-12">
    <div class=" card">
        <div class=" card-header text-center">
            <h5> Crear Categoria</h5>
        </div>
        <div class=" card-body text-center">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label></label>
                    <input asp-for="Nombre" class="form-control" placeholder=" Nombre" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>               
                <div class=" card-footer ">
                    <div class="form-group">
                        <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
                        <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Biblioteca/Biblioteca.Frontend/Views/Categorias/Edit.cshtml
@model Biblioteca.Frontend.Models.Categoria
@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<div class=" col-md-12">
    <div class=" card">
        <div class=" card-header text-center">
            <h5> Editar Categoria</h5>
        </div>
        <div class=" card-body text-center">
            <form asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                               
                <div class="form-group">
                    <label></label>
                    <input asp-for="Nombre" class="form-control" placeholder=" Nombre" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
               
                <div class=" card-footer ">
                    <div class="form-group">
                        <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
                        <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Biblioteca/Biblioteca.Frontend/Views/Categorias/Index.cshtml
@model IEnumerable<Biblioteca.Frontend.Models.Categoria>
@{
    ViewData["Title"] = "Index";
}

@section Estilos {
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["AlertMessage"] != null)
{
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            Swal.fire({
                title: '¡Éxito!',
                text: '@TempData["AlertMessage"]',
                icon: 'success',
                confirmButtonText: 'Aceptar'
            });
        });
    </script>
}

@if (TempData["ErrorMessage"] != null)
{
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            Swal.fire({
                title: '¡Error!',
                text: '@TempData["ErrorMessage"]',
                icon: 'error',
                confirmButtonText: 'Aceptar'
            });
        });
    </script>
}

@if (TempData["ModelErrors"] != null)
{
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            Swal.fire({
                title: 'Errores de Validación',
                text: '@TempData["ModelErrors"]',
                icon: 'error',
                confirmButtonText: 'Aceptar'
            });
        });
    </script>
}

<p>
    <a onclick="showInPopup('@Url.Action("Create", "Categorias", new { id = 0 }, Context.Request.Scheme)' , '')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> Agregar una categoria</a>
</p>

<div class="col-md-12">
    <div class="card">
        <div class="card-header text-center">
            <h5>Lista de Categorias</h5>
        </div>
        <div class="card-body">
            <table id="categoria" class="table table-hover table responsive table stripped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.Id</th>
                            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                            <td>
                                <a onclick="showInPopup('@Url.Action("Edit", "Categorias", new { id = item.Id }, Context.Request.Scheme)' ,
                    '')" class="btn btn-outline-warning btn-sm"><i class="fa fa-pencil-alt"></i> </a>
                                <button data-id="@item.Id" class="btn btn-outline-danger btn-sm deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<partial name="_MostrarModal" />
<partial name="_ModalEliminar" />

@section Scripts {

    <partial name="_ValidationScriptsPartial" />

    <script src="~/js/showmodal.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#categoria').DataTable({
                "language": {
                    url: "https://cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
                },
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Categorias/Delete/', false);
    </script>
}